version: "3.3"
services:
  frontend_app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: sh -c "yarn && yarn dev"
